# API Testing
GET http://localhost:3000/

###
# GET : All Notes (lihat semua catatan)
GET http://localhost:3000/api/v1/notes
Content-Type: application/json

###
# GET : Note by ID (ambil berdasarkan id)
GET http://localhost:3000/api/v1/notes/7
Content-Type: application/json

###
# POST : Create Note (tambah catatan baru)
POST http://localhost:3000/api/v1/notes
Content-Type: application/json

{
  "judul": "Ez",
  "isi": "Membuat CRUD Notes dengan Express dan Sequelize(MU masuk UCL)"
}

###
# PUT : Update Note
PUT http://localhost:3000/api/v1/notes/3
Content-Type: application/json

{
  "judul": "HomeComing",
  "isi": "Alhamdulillah MUDAH SELESAI"
}

###
# DELETE : Delete Note
DELETE http://localhost:3000/api/v1/notes/6
Content-Type: application/json